<?php

namespace Test;

use Creational\POOL\Car;
use Creational\POOL\CarPool;
use PHPUnit\Framework\TestCase;

class PoolTest extends TestCase
{
    private $carPool;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->carPool = new CarPool();
    }

    public function testCanRentCar()
    {
        $myCar1 = $this->carPool->rentCar();
        $myCar2 = $this->carPool->rentCar();
        $myCar3 = $this->carPool->rentCar();
        $this->assertInstanceOf(Car::class, $myCar1);
        $this->assertEquals(3, $this->carPool->getReport());
    }

    public function testCanFreeCar()
    {
        $myCar1 = $this->carPool->rentCar();
        $this->carPool->freeCar($myCar1);

        $myCar1 = $this->carPool->rentCar();

        $this->assertEquals(0, $this->carPool->getFreeCount());
        $this->assertEquals(1, $this->carPool->getReport());
    }

}